#!/bin/bash

## Open folders in thunar
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--dl" ]]; then
	close_dash && thunar ~/Downloads &

elif [[ "$1" == "--docs" ]]; then
	close_dash && thunar ~/Documents &

elif [[ "$1" == "--5sem" ]]; then
	close_dash && thunar ~/Sem5 &

elif [[ "$1" == "--pics" ]]; then
	close_dash && thunar ~/Pictures &

elif [[ "$1" == "--cfg" ]]; then
	close_dash && thunar ~/.config &

fi
