#!/bin/bash

max_brightness=$(brightnessctl max)
current_brightness=$(brightnessctl g)
brightness_percentage=$((($current_brightness * 100) / $max_brightness))

down() {
    brightnessctl s 5%-
    current_brightness=$(brightnessctl g)
    brightness_percentage=$((($current_brightness * 100) / $max_brightness))
    dunstify -a "BRIGHTNESS" "Decreasing to $brightness_percentage%" -h int:value:"$brightness_percentage" -i display-brightness-symbolic -r 2593 -u normal
}

up() {
    brightnessctl s +5%
    current_brightness=$(brightnessctl g)
    brightness_percentage=$((($current_brightness * 100) / $max_brightness))
    dunstify -a "BRIGHTNESS" "Increasing to $brightness_percentage%" -h int:value:"$brightness_percentage" -i display-brightness-symbolic -r 2593 -u normal
}

case "$1" in
  up) up;;
  down) down;;
esac
